atcoder:
  enable: true
  user_id: ""
  outdir: "AtCoder/"
  outformat: "file"
  use_index: false
  archive_targets: "ac_latest"
  git_commit: "none"
aoj:
  enable: false
  user_id: ""
  out_dir: "AOJ/"
  outformat: "file"
  use_index: false
  archive_targets: "ac_latest"
  git_commit: "none"
codeforces:
  enable: false
  user_id: ""
  outdir: "Codeforces/"
  outformat: "file"
  use_index: false
  archive_targets: "ac_latest"
  git_commit: "none"
